# HA Fleet Services
get_logs:
  name: Get logs
  description: Retrieve Home Assistant log file contents
  fields:
    lines:
      name: Lines
      description: Number of lines to retrieve from the end of the log file
      required: false
      default: 200
      example: 100
      selector:
        number:
          min: 10
          max: 1000
          step: 10

update_integration:
  name: Update integration
  description: Update HA Fleet integration to the latest version from GitHub
  fields:
    branch:
      name: Branch
      description: GitHub branch to download from
      required: false
      default: "master"
      example: "master"
      selector:
        text:
